apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guild-tls
  namespace: guild
spec:
  secretName: guild-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - guild.inevitable.fyi
